import type { Article } from "./types";

export const areaArticles: Article[] = [
  {
    id: "a24",
    title: "都市の選び方｜主要エリアの特徴と向いている人",
    slug: "area-overview",
    category: "area",
    description:
      "シドニー・メルボルン・ブリスベン・パース・ケアンズ・ゴールドコースト。生活費・仕事・気候の違いを比較し、自分に合う都市を選ぶための総合ガイド。",
    content: [
      "どの都市を拠点にするかで、ワーホリの体験は大きく変わります。仕事の多さ・物価・気候・日本人コミュニティの規模はそれぞれ異なるため、自分の優先順位（稼ぎたい/英語環境/のんびり/ビーチ）で選ぶのがおすすめです。",
      "迷ったら、まず仕事が多い大都市（シドニー・メルボルン・ブリスベン）でスタートし、慣れてから地方やファームに移動する人が多いです。各都市の詳細は個別のエリアガイドを参照してください。",
    ],
    keyFacts: [
      { label: "仕事が多い", value: "シドニー・メルボルン・ブリスベン" },
      { label: "物価が高め", value: "シドニー・メルボルン" },
      { label: "温暖で過ごしやすい", value: "ブリスベン・ゴールドコースト・パース" },
      { label: "ファーム拠点に便利", value: "ケアンズ・地方都市" },
    ],
    steps: [
      { title: "優先順位を決める", description: "稼ぎ・英語環境・気候・コミュニティのどれを重視するか整理します。" },
      { title: "拠点都市を選ぶ", description: "最初は仕事の多い大都市が無難。生活に慣れてから移動を検討します。" },
      { title: "移動も前提に計画", description: "セカンドビザのファームや旅行で都市間移動するワーホリは多いです。" },
    ],
    tips: [
      "都市間の移動は格安航空（Jetstar、Virgin等）が便利。早割で安く移動できます。",
      "シェアハウスは都市の中心部ほど高くなります。郊外＋公共交通の組み合わせも検討しましょう。",
    ],
    relatedSlugs: ["area-sydney", "area-melbourne", "area-brisbane", "housing-guide"],
    updatedAt: "2026-06-10",
    published: true,
  },

  {
    id: "a25",
    title: "シドニー エリアガイド｜仕事・家賃・暮らしの実情",
    slug: "area-sydney",
    category: "area",
    description:
      "オーストラリア最大都市シドニー。仕事の多さと家賃の高さ、住みやすいエリア、交通事情まで、拠点選びに役立つ情報をまとめました。",
    content: [
      "シドニーはオーストラリア最大の都市で、仕事の数・種類ともに最多。ジャパレスからローカルのカフェ・小売・オフィスワークまで選択肢が豊富で、英語環境も日本人コミュニティも充実しています。その分、家賃と物価は国内でもっとも高い水準です。",
      "シティ（CBD）周辺は家賃が高いため、ワーホリはInner West（Newtown等）や、電車・バスでアクセスしやすい郊外にシェアハウスを借りる人が多いです。ビーチが好きならBondiやCoogee周辺も人気です。",
    ],
    keyFacts: [
      { label: "特徴", value: "仕事が最多・物価最高・都会的" },
      { label: "家賃目安(シェア)", value: "週180〜350 AUD（エリア・個室/相部屋で変動）" },
      { label: "交通", value: "Opalカードで電車・バス・フェリーが利用可" },
      { label: "向いている人", value: "稼ぎたい・選択肢を広く持ちたい人" },
    ],
    steps: [
      { title: "エリアを絞る", description: "予算と通勤を考え、Inner Westや郊外＋電車通勤などを検討します。" },
      { title: "Opalカードを用意", description: "交通はOpalのタッチ決済（対応クレカ/スマホでも可）が便利です。" },
      { title: "仕事を探す", description: "求人数が多いので、ジャパレス→ローカルへのステップアップもしやすいです。" },
    ],
    tips: [
      "週末のOpalは運賃上限があり、観光や遠出がしやすいです。",
      "家賃が高い分、時給の高いローカルジョブを狙うと収支が安定します。",
    ],
    relatedSlugs: ["area-overview", "housing-guide", "jobs-guide"],
    updatedAt: "2026-06-10",
    published: true,
  },

  {
    id: "a26",
    title: "メルボルン エリアガイド｜カフェ文化と暮らしやすさ",
    slug: "area-melbourne",
    category: "area",
    description:
      "『世界一住みやすい都市』に何度も選ばれたメルボルン。カフェ文化、トラム、気候、仕事事情まで、拠点選びのポイントを解説します。",
    content: [
      "メルボルンは芸術・カフェ文化で知られる洗練された都市。バリスタやカフェの仕事が豊富で、ローカルのホスピタリティ経験を積みたい人に人気です。市内中心部はトラム（路面電車）が発達し、フリーゾーンでは無料で乗れます。",
      "気候は四季がはっきりし、『1日で四季がある』と言われるほど寒暖差が大きいのが特徴。シドニーよりやや家賃が落ち着いていることもあり、長期で腰を据えたいワーホリに向いています。",
    ],
    keyFacts: [
      { label: "特徴", value: "カフェ文化・芸術・住みやすさ" },
      { label: "家賃目安(シェア)", value: "週160〜320 AUD" },
      { label: "交通", value: "mykiカードでトラム・電車・バス。市内に無料トラムゾーン" },
      { label: "向いている人", value: "カフェ就労・落ち着いた都市生活を求める人" },
    ],
    steps: [
      { title: "mykiを用意", description: "メルボルンの公共交通はmykiカードで利用します。" },
      { title: "バリスタスキルを磨く", description: "カフェ就労が多いので、コーヒー経験があると有利です。" },
      { title: "防寒対策", description: "寒暖差が大きいので重ね着できる服装を準備します。" },
    ],
    tips: [
      "市内中心の『Free Tram Zone』内はトラムが無料。生活圏に入れると交通費を抑えられます。",
      "気温が1日で大きく変わるため、上着は年間を通して手元に置くと安心です。",
    ],
    relatedSlugs: ["area-overview", "clothing-guide", "jobs-guide"],
    updatedAt: "2026-06-10",
    published: true,
  },

  {
    id: "a27",
    title: "ブリスベン エリアガイド｜温暖で暮らしやすいクイーンズランドの州都",
    slug: "area-brisbane",
    category: "area",
    hub: "area",
    description:
      "クイーンズランド州の州都ブリスベン。温暖な気候と大都市よりゆとりのある暮らしやすさ、仕事・交通・拠点選びのポイントをワーホリ目線でまとめました。",
    content: [
      "ブリスベンは『大都市の便利さ』と『温暖で落ち着いた暮らし』のバランスがよく、初めてのワーホリの拠点として人気です。クイーンズランド州の州都で、シドニー・メルボルンに次ぐ規模。ジャパレスからローカルのカフェ・小売・オフィスワークまで仕事の選択肢があり、亜熱帯気候で冬も過ごしやすいのが魅力です。",
      "公共交通は電車・バス・フェリー（CityCat）が使え、Translink の go card（タッチ決済対応）で乗車します。CBD 周辺は家賃が高めのため、電車やバスでつながる郊外にシェアハウスを借りるワーホリが多いです。",
      "車で1時間ほど南のゴールドコーストはビーチリゾートで生活の雰囲気が異なるため、別記事『ゴールドコースト エリアガイド』で詳しく解説しています。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）の州都" },
      { label: "特徴", value: "亜熱帯で温暖・大都市より落ち着いた暮らし" },
      { label: "交通", value: "Translink go card で電車・バス・フェリー（CityCat）" },
      { label: "家賃", value: "エリア・時期で変動。最新は Flatmates・realestate.com.au で確認" },
      { label: "向いている人", value: "初めてのワーホリ・温暖な気候・コスパ重視" },
    ],
    steps: [
      { title: "go card を用意", description: "QLD の公共交通は Translink の go card（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "エリアを絞る", description: "予算と通勤を考え、電車・バス沿線の郊外シェアハウスを検討します。" },
      { title: "仕事を探す", description: "ジャパレス→ローカルへのステップアップがしやすい都市です。求人サイトや店頭応募を併用します。" },
    ],
    tips: [
      "亜熱帯気候で冬も比較的暖かく、寒さが苦手な人に過ごしやすい地域です。",
      "夏は紫外線と暑さが強いので、日焼け対策と水分補給をしっかりと（UV は ARPANSA、天気は BOM で確認）。",
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-27" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-overview", "area-gold-coast", "housing-guide", "jobs-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a28",
    title: "パース vs ケアンズ｜西海岸と熱帯北部、どっちを拠点にする？",
    slug: "area-perth-cairns",
    category: "area",
    hub: "area",
    description:
      "西オーストラリアのパースと、熱帯クイーンズランドのケアンズ。国の東西で性格が大きく異なる2都市を、仕事・気候・拠点適性で比較し、選び方を整理します。",
    content: [
      "パースとケアンズは、どちらも『大都市以外の拠点』として人気ですが、場所も暮らしも大きく異なります。結論から言うと、落ち着いた都市生活と西海岸を楽しみたいならパース、観光やファーム（セカンドビザ）を軸に熱帯の北部で過ごしたいならケアンズが向いています。",
      "パースは西オーストラリア州の州都で、東海岸から離れた独立した大都市。ケアンズは熱帯の観光都市で、周辺にファーム地域が広がりセカンドビザの拠点になります。両都市の詳細は、それぞれの専用ガイドにまとめています。",
    ],
    keyFacts: [
      { label: "パース", value: "WA の州都・都市生活・西海岸。詳細は専用ガイドへ" },
      { label: "ケアンズ", value: "熱帯・観光・ファーム拠点。詳細は専用ガイドへ" },
      { label: "選び方", value: "都市生活＝パース／観光・セカンドビザ＝ケアンズ" },
    ],
    steps: [
      { title: "目的を決める", description: "都市で働く・英語環境重視ならパース、観光やファームでセカンドビザを狙うならケアンズを軸に検討します。" },
      { title: "専用ガイドを読む", description: "『パース エリアガイド』『ケアンズ エリアガイド』で仕事・交通・気候・空港を確認します。" },
      { title: "移動と気候を考慮", description: "パースは時差（AWST）、ケアンズは雨季・サイクロン期があります。渡航時期と合わせて選びます。" },
    ],
    relatedSlugs: ["area-perth", "area-cairns", "area-overview", "farm-second-visa", "second-visa-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a41",
    title: "アデレード エリアガイド｜物価が落ち着いた南オーストラリアの州都",
    slug: "area-adelaide",
    category: "area",
    description:
      "大都市より家賃・物価が抑えめで、のんびり暮らせる南オーストラリア州の州都アデレード。ワインの名産地で、落ち着いた生活を求める人に人気です。",
    content: [
      "アデレードは南オーストラリア州の州都で、東海岸の大都市に比べて家賃・物価が落ち着いているのが魅力です。街がコンパクトで治安も良く、のんびりとしたペースで暮らしたいワーホリに向いています。",
      "周辺はバロッサ・バレーなど世界的なワインの産地で、ぶどうの収穫やワイナリーの仕事（季節労働）も見つかります。大都市ほど求人数は多くありませんが、その分競争が穏やかで、生活コストを抑えながらじっくり滞在できます。",
    ],
    keyFacts: [
      { label: "特徴", value: "物価控えめ・コンパクト・治安良好" },
      { label: "家賃目安(シェア)", value: "週130〜240 AUD" },
      { label: "交通", value: "metroCARDで電車・トラム・バス。無料区間あり" },
      { label: "向いている人", value: "生活費を抑えたい・落ち着いた環境を好む人" },
    ],
    steps: [
      { title: "metroCARDを用意", description: "アデレードの公共交通はmetroCARDで利用します。" },
      { title: "拠点を決める", description: "コンパクトな街なので中心部周辺でも比較的家賃が手頃です。" },
      { title: "季節労働も視野に", description: "周辺のワイナリー・農園で収穫期の仕事を探せます。" },
    ],
    tips: [
      "シティ中心部にはトラムや電車の無料区間があり、交通費を抑えられます。",
      "大都市より求人は少なめ。仕事優先なら他都市と比較しつつ検討しましょう。",
    ],
    relatedSlugs: ["area-overview", "farm-finding", "housing-guide"],
    updatedAt: "2026-06-20",
    published: true,
  },

  {
    id: "a297",
    title: "ゴールドコースト エリアガイド｜仕事・家賃・交通・ビーチ生活",
    slug: "area-gold-coast",
    category: "area",
    hub: "area",
    description:
      "サーファーズパラダイスで知られるゴールドコースト。観光・ホスピタリティの仕事、ビーチ中心の暮らし、交通・気候・空港まで、ワーホリの拠点選びに役立つ情報をまとめました。",
    content: [
      "ゴールドコーストは、観光・ホスピタリティの仕事が多く、ビーチ中心のアクティブな生活を送りたいワーホリに向いた拠点です。クイーンズランド州南東部、ブリスベンから電車・車で約1時間の距離にあり、温暖な気候と長いビーチが魅力です。",
      "観光地のため、カフェ・レストラン・バー、ホテル、小売、テーマパーク（サーファーズパラダイス周辺）など接客・ホスピタリティ系の求人が中心で、建設や清掃の仕事もあります。観光シーズンやイベントで需要が動くため、最新の募集状況は求人サイトや店頭で確認しましょう。",
      "公共交通は Gold Coast Light Rail（G:link・路面電車）と路線バスが中心で、Translink の go card（タッチ決済対応）で乗車します。ビーチ沿いの主要エリアは Light Rail でつながっていますが、郊外や内陸は本数が限られるため、車があると生活の幅が広がります。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）南東部（ブリスベンから約1時間）" },
      { label: "特徴", value: "観光・ビーチ・温暖な亜熱帯気候" },
      { label: "交通", value: "Gold Coast Light Rail（G:link）＋バス／go card" },
      { label: "空港", value: "Gold Coast Airport（OOL・Coolangatta）。ブリスベン空港も利用可" },
      { label: "家賃", value: "変動。最新は Flatmates・realestate.com.au で確認" },
      { label: "向いている人", value: "観光・接客で働きたい／ビーチ生活重視" },
    ],
    steps: [
      { title: "go card を用意", description: "QLD の公共交通は Translink の go card（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "ビーチ沿いか内陸かを選ぶ", description: "通勤とライフスタイルに合わせ、Light Rail 沿線か、家賃が抑えめの内陸かを検討します。" },
      { title: "接客・観光求人を探す", description: "ホスピタリティは RSA（責任あるアルコール提供）があると有利。求人サイトと店頭応募を併用します。" },
    ],
    tips: [
      "Light Rail（G:link）沿線は生活・通勤に便利で、車なしでも動きやすいエリアです。",
      "夏は UV と暑さが強く、スコールや雷雨もあります。日焼け・熱中症対策を（UV は ARPANSA、天気は BOM で確認）。",
    ],
    faqs: [
      {
        question: "ブリスベンとゴールドコースト、どちらを拠点にすべき？",
        answer:
          "仕事の数・選択肢の広さを重視するならブリスベン、観光・接客の仕事とビーチ中心の生活を重視するならゴールドコーストが向いています。電車で行き来できる距離なので、住んでみて移ることもできます。",
      },
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・G:link 運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-27" },
      { label: "Gold Coast Airport（OOL・空港アクセス）", url: "https://www.goldcoastairport.com.au/", accessedAt: "2026-07-27" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-brisbane", "area-overview", "jobs-guide", "housing-guide", "transport-payment-guide", "clothing-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a298",
    title: "パース エリアガイド｜仕事・家賃・車・西海岸生活",
    slug: "area-perth",
    category: "area",
    hub: "area",
    description:
      "西オーストラリア州の州都パース。東海岸から離れた独立した大都市で、晴天と西海岸の暮らし、仕事・交通・時差・空港まで、拠点選びに役立つ情報をまとめました。",
    content: [
      "パースは西オーストラリア州（WA）の州都で、東海岸の大都市から離れた独立した大都市。落ち着いた都市生活と美しいビーチ・日照を楽しめ、英語環境に集中したいワーホリにも人気です。",
      "仕事はホスピタリティ・小売・清掃・建設などがあります。WA は鉱業（マイニング）・資源産業が盛んで関連の仕事が話題になりますが、条件や賃金は職種・資格で大きく変わるため、具体的な金額は募集ごとに確認してください。地方（Regional WA）ではセカンドビザ対象の仕事が見つかることもあります。",
      "公共交通は Transperth が運営する電車・バス・フェリーで、SmartRider カードで乗車します。CBD 内は無料の CAT バスが走っています。都市が広く、郊外や地方へは車が便利です。西オーストラリアは AWST で東海岸（シドニー等）と時差があり、東部が夏時間の時期はさらに差が開くため、日本との連絡やフライト予約時に注意しましょう。",
    ],
    keyFacts: [
      { label: "州", value: "西オーストラリア州（WA）の州都" },
      { label: "特徴", value: "独立した大都市・晴天と西海岸・地中海性気候" },
      { label: "交通", value: "Transperth（電車・バス・フェリー）／SmartRider・CBD は無料 CAT バス" },
      { label: "空港", value: "Perth Airport（PER）" },
      { label: "時差", value: "東海岸と時差あり（AWST）" },
      { label: "家賃", value: "変動。最新は Flatmates・realestate.com.au で確認" },
    ],
    steps: [
      { title: "SmartRider を用意", description: "パースの公共交通は Transperth の SmartRider で利用します。CBD 内は無料 CAT バスが便利です。" },
      { title: "エリアを選ぶ", description: "電車・バス沿線でシェアハウスを探すと通勤しやすくなります。地方移動を考えるなら車も検討します。" },
      { title: "仕事を探す", description: "ホスピタリティ・小売・建設などを求人サイトと店頭で探します。地方はセカンドビザ対象の仕事も視野に入れます。" },
    ],
    tips: [
      "CBD 内の無料 CAT バスを使うと交通費を抑えられます。",
      "東海岸との時差があるため、面接や日本との連絡は時間帯を確認して調整しましょう。",
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Transperth（WA 公共交通・SmartRider・運賃）", url: "https://www.transperth.wa.gov.au/", accessedAt: "2026-07-27" },
      { label: "Perth Airport（PER・空港アクセス）", url: "https://www.perthairport.com.au/", accessedAt: "2026-07-27" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-perth-cairns", "area-cairns", "area-overview", "jobs-guide", "housing-guide", "second-visa-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a299",
    title: "ケアンズ エリアガイド｜観光業・気候・ファームへの移動",
    slug: "area-cairns",
    category: "area",
    hub: "area",
    description:
      "熱帯クイーンズランド北部の観光都市ケアンズ。観光・ホスピタリティの仕事と、周辺ファームへの拠点としての使い方、気候・交通・空港をワーホリ目線でまとめました。",
    content: [
      "ケアンズは熱帯クイーンズランド北部（Far North QLD）の観光都市で、グレートバリアリーフ観光の玄関口。観光・ホスピタリティの仕事に加え、周辺にファーム地域が広がるため、セカンドビザ（88日）を目指すワーホリの拠点として人気です。",
      "仕事は観光・ホスピタリティ（ツアー、ダイビング、ホテル、飲食）が中心。周辺の Atherton Tablelands・Mareeba などはバナナ・アボカド・ベリーなどのファーム求人があり、収穫期に需要が動きます。ファームは悪質な求人・農園もあるため、雇用主やセカンドビザ対象かを事前に確認しましょう。",
      "市内は路線バス（Sunbus）が中心で、鉄道・トラムはありません。運賃・路線は変わることがあるため、最新は Translink／Queensland Government で確認を。周辺のファーム地域へ通うには車があると有利です。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）北部（Far North）" },
      { label: "特徴", value: "熱帯・観光・ファーム拠点" },
      { label: "交通", value: "路線バス（Sunbus）中心／周辺ファームは車が便利" },
      { label: "空港", value: "Cairns Airport（CNS）" },
      { label: "気候", value: "熱帯・雨季（11〜4月頃）・サイクロン注意" },
      { label: "向いている人", value: "観光で働きたい／ファームでセカンドビザを狙う" },
    ],
    steps: [
      { title: "拠点を決める", description: "観光の仕事中心なら市内、ファーム中心なら周辺地域（Atherton Tablelands・Mareeba 等）への移動を前提に検討します。" },
      { title: "ファーム情報を集める", description: "収穫期に合わせて求人を探し、雇用主がセカンドビザ対象か・労働条件を確認します。" },
      { title: "移動手段を確保", description: "ファーム地域へは車があると仕事・生活の選択肢が広がります。相乗りや送迎の有無も確認します。" },
    ],
    tips: [
      "雨季（おおむね11〜4月）は高温多湿でスコールが多く、サイクロンの可能性もあります。BOM の気象・警報を確認しましょう。",
      "ファームは条件が農園ごとに異なります。悪質農園を避けるため、応募前に評判・契約・支払い方法を確認しましょう。",
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Bureau of Meteorology｜Climate averages・気象警報（雨季・サイクロン）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-27" },
      { label: "Cairns Airport（CNS・空港アクセス）", url: "https://www.cairnsairport.com.au/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-perth-cairns", "area-perth", "area-overview", "farm-second-visa", "region-mareeba-atherton-farm", "second-visa-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a300",
    title: "キャンベラ エリアガイド｜仕事・家賃・交通",
    slug: "area-canberra",
    category: "area",
    hub: "area",
    description:
      "オーストラリアの首都キャンベラ。計画的に整備された落ち着いた都市での仕事・交通・気候を、ワーホリの拠点選び目線でまとめました。",
    content: [
      "キャンベラはオーストラリアの首都で、計画的に整備された落ち着いた都市。大都市ほど求人は多くありませんが、ホスピタリティ・小売・事務などの仕事があり、静かな環境で暮らしたいワーホリに向いています。",
      "政府機関が集まる街ですが、ワーホリはカフェ・レストラン・小売・清掃・イベントなどの仕事が中心です。求人数は大都市より少なめのため、求人サイト・店頭応募・人材会社など複数の探し方を併用しましょう。",
      "公共交通は Transport Canberra が運営する Light Rail（ライトレール）とバスで、MyWay カードで乗車します。街が広く、エリアによっては車があると便利です。",
    ],
    keyFacts: [
      { label: "地域", value: "オーストラリア首都特別地域（ACT）" },
      { label: "特徴", value: "首都・計画都市・落ち着いた環境" },
      { label: "交通", value: "Transport Canberra（Light Rail＋バス）／MyWay" },
      { label: "空港", value: "Canberra Airport（CBR）" },
      { label: "気候", value: "内陸・冬は冷え込み霜／夏は暑く乾燥" },
      { label: "向いている人", value: "静かな環境・接客/事務で働きたい" },
    ],
    steps: [
      { title: "MyWay を用意", description: "キャンベラの公共交通は MyWay カードで利用します。" },
      { title: "拠点を選ぶ", description: "Light Rail・バス沿線でシェアハウスを探すと移動しやすくなります。" },
      { title: "仕事を複数の方法で探す", description: "求人数が少なめのため、求人サイト・店頭応募・人材会社を併用します。" },
    ],
    tips: [
      "内陸で寒暖差が大きく、冬（6〜8月）は朝晩が冷え込み霜が降りることもあります。防寒具を用意しましょう（気候は BOM で確認）。",
      "求人が大都市より少なめなので、早めに動き、探し方を複数持つと安心です。",
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Transport Canberra（ACT 公共交通・Light Rail・MyWay）", url: "https://www.transport.act.gov.au/", accessedAt: "2026-07-27" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-sydney", "area-overview", "jobs-guide", "housing-guide", "clothing-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a301",
    title: "ホバート エリアガイド｜タスマニアの仕事と暮らし",
    slug: "area-hobart",
    category: "area",
    hub: "area",
    description:
      "タスマニア州の州都ホバート。自然と歴史的な街並みが魅力の落ち着いた都市での仕事・季節労働・交通・気候を、ワーホリ目線でまとめました。",
    content: [
      "ホバートはタスマニア州（TAS）の州都で、自然と歴史的な街並みが魅力の落ち着いた都市。観光・ホスピタリティの仕事があり、周辺の農業地域は収穫期の季節労働（セカンドビザ対象になり得る）で知られます。のんびり暮らしたい人や、タスマニアでファームを考える人の拠点になります。",
      "仕事は観光・飲食・小売・宿泊が中心。周辺〜州内はチェリー・ベリー・りんごなどの収穫やアクアカルチャー（養殖）の季節労働があり、時期により需要が動きます。セカンドビザを狙う場合は、対象作業・地域かを事前に確認しましょう。",
      "公共交通は Metro Tasmania の路線バスが中心で、Greencard で乗車します。鉄道・トラムはありません。州内の移動やファーム地域へは車があると便利です。",
    ],
    keyFacts: [
      { label: "州", value: "タスマニア州（TAS）の州都" },
      { label: "特徴", value: "自然・落ち着いた都市・冷涼な気候" },
      { label: "交通", value: "Metro Tasmania（路線バス）／Greencard・鉄道/トラムなし" },
      { label: "空港", value: "Hobart Airport（HBA）" },
      { label: "気候", value: "冷涼・冬は本土より寒い／UV は夏に強い" },
      { label: "向いている人", value: "のんびり暮らしたい／タスマニアでファームを考える" },
    ],
    steps: [
      { title: "Greencard を用意", description: "ホバートの公共交通は Metro Tasmania の Greencard で利用します。" },
      { title: "拠点を選ぶ", description: "市内で観光・飲食の仕事、周辺で季節労働など、目的に合わせて拠点を決めます。" },
      { title: "季節労働を探す", description: "チェリー・ベリー・りんごなどはシーズンが限られます。時期を確認して早めに動きます。" },
    ],
    tips: [
      "冷涼な気候で冬（6〜8月）は本土より寒く、山間部では雪も。防寒対策を用意しましょう（気候は BOM で確認）。",
      "季節労働はシーズンが限られるため、収穫時期に合わせて計画しましょう。",
    ],
    verifiedAt: "2026-07-27",
    officialSources: [
      { label: "Metro Tasmania（TAS 公共交通・Greencard・運賃）", url: "https://www.metrotas.com.au/", accessedAt: "2026-07-27" },
      { label: "Hobart Airport（HBA・空港アクセス）", url: "https://www.hobartairport.com.au/", accessedAt: "2026-07-27" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-27" },
    ],
    relatedSlugs: ["area-melbourne", "area-overview", "farm-second-visa", "region-tasmania-farm", "jobs-guide", "clothing-guide"],
    updatedAt: "2026-07-27",
    published: true,
  },

  {
    id: "a302",
    title: "ダーウィン エリアガイド｜乾季・雨季・仕事・北部の暮らし",
    slug: "area-darwin",
    category: "area",
    hub: "area",
    description:
      "オーストラリア北部、ノーザンテリトリーの州都ダーウィン。乾季・雨季がはっきりした熱帯気候、観光・建設・季節労働の仕事、交通・空港まで、ワーホリの拠点選びに役立つ情報をまとめました。",
    content: [
      "ダーウィンはノーザンテリトリー（NT）の州都で、東海岸の大都市から離れた熱帯の街。観光・ホスピタリティに加え、建設や季節労働（Specified Work・セカンドビザ対象になり得る仕事）があり、東海岸とは違う環境で過ごしたいワーホリの拠点になります。",
      "気候は熱帯で、1年が乾季（おおむね5〜10月）と雨季（おおむね11〜4月）に分かれます。雨季は高温多湿でスコールや雷雨が多く、サイクロンの可能性もあります。渡航や仕事の時期は BOM の気象・警報を確認しましょう。",
      "仕事は観光・飲食・宿泊のほか、建設や農業・季節労働があります。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう（対象は Home Affairs の案内で確認）。求人数は大都市より限られるため、複数の探し方を併用します。",
      "公共交通は NT の路線バスが中心で、鉄道・トラムはありません。街が広く、周辺や地方へは車があると便利です。空港はダーウィン国際空港（DRW）。",
    ],
    keyFacts: [
      { label: "地域", value: "ノーザンテリトリー（NT）の州都" },
      { label: "特徴", value: "熱帯・乾季/雨季・東海岸とは違う環境" },
      { label: "交通", value: "NT の路線バス中心／周辺・地方は車が便利" },
      { label: "空港", value: "Darwin International Airport（DRW）" },
      { label: "気候", value: "乾季（5〜10月頃）・雨季（11〜4月頃）・サイクロン注意" },
      { label: "向いている人", value: "観光/建設/季節労働で働きたい・北部で過ごしたい" },
    ],
    steps: [
      { title: "渡航時期を決める", description: "乾季（過ごしやすい）と雨季（高温多湿・サイクロン期）で環境が大きく変わります。目的に合わせて選びます。" },
      { title: "仕事を探す", description: "観光・建設・季節労働を求人サイトや店頭で探します。セカンドビザ狙いは対象作業・対象地域かを確認します。" },
      { title: "移動手段を確保", description: "公共交通が限られるため、周辺や地方で働くなら車や送迎の有無を確認します。" },
    ],
    tips: [
      "雨季（11〜4月頃）はスコール・雷雨が多く、サイクロンの可能性もあります。BOM の気象・警報を確認しましょう。",
      "建設・季節労働は対象要件や労働条件を事前に確認し、悪質な求人には注意しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Northern Territory Government｜Public transport（NT のバス）", url: "https://nt.gov.au/driving/public-transport-cycling", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Darwin International Airport（DRW・空港アクセス）", url: "https://www.darwinairport.com.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages・気象警報（乾季/雨季・サイクロン）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-cairns", "area-overview", "farm-second-visa", "second-visa-guide", "specified-work-postcodes", "jobs-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a303",
    title: "サンシャインコースト エリアガイド｜観光・飲食・交通・家賃",
    slug: "area-sunshine-coast",
    category: "area",
    hub: "area",
    description:
      "クイーンズランド州南東部のサンシャインコースト。ビーチと観光の街で、飲食・ホスピタリティの仕事や、交通・気候・空港まで、ワーホリの拠点選びに役立つ情報をまとめました。",
    content: [
      "サンシャインコーストはクイーンズランド州南東部、ブリスベンの北にあるビーチリゾート。温暖な気候と観光・飲食の仕事があり、ゴールドコーストほど賑やかすぎない環境で過ごしたいワーホリに向いています。",
      "観光地のため、カフェ・レストラン・バー、ホテル、小売など接客・ホスピタリティ系の求人が中心です。観光シーズンで需要が動くため、最新の募集は求人サイトや店頭で確認しましょう。",
      "公共交通は路線バスが中心で、Translink の go card（タッチ決済対応）で乗車します。エリアが広く海沿いに点在するため、車があると生活の幅が広がります。ブリスベンとは鉄道でもつながっています。",
      "亜熱帯気候で1年を通じて温暖。夏は紫外線と暑さが強く、日焼け対策を（UV は ARPANSA、天気は BOM で確認）。家賃はエリア・時期で変動するため、最新は Flatmates・realestate.com.au で確認しましょう。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）南東部（ブリスベンの北）" },
      { label: "特徴", value: "観光・ビーチ・温暖な亜熱帯気候" },
      { label: "交通", value: "路線バス＋鉄道／Translink go card。車があると便利" },
      { label: "空港", value: "Sunshine Coast Airport（MCY）。ブリスベン空港も利用可" },
      { label: "家賃", value: "変動。最新は Flatmates・realestate.com.au で確認" },
      { label: "向いている人", value: "観光・接客で働きたい・落ち着いたビーチ生活" },
    ],
    steps: [
      { title: "go card を用意", description: "QLD の公共交通は Translink の go card（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "エリアを選ぶ", description: "海沿いに拠点が点在するため、通勤とライフスタイルに合わせてエリアを絞ります。車があると便利です。" },
      { title: "接客・観光求人を探す", description: "ホスピタリティは RSA（責任あるアルコール提供）があると有利。求人サイトと店頭応募を併用します。" },
    ],
    tips: [
      "エリアが広く海沿いに点在するため、車があると移動と仕事探しが楽になります。",
      "夏は UV と暑さが強く、スコールもあります。日焼け・熱中症対策を（UV は ARPANSA、天気は BOM で確認）。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Sunshine Coast Airport（MCY・空港アクセス）", url: "https://www.sunshinecoastairport.com.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-brisbane", "area-gold-coast", "area-overview", "jobs-guide", "housing-guide", "transport-payment-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a304",
    title: "トゥーンバ・ガトン エリアガイド｜地方生活・ファーム・車",
    slug: "area-toowoomba-gatton",
    category: "area",
    hub: "area",
    description:
      "クイーンズランド州内陸のトゥーンバとガトン（ロッキャーバレー）。野菜を中心としたファーム地域で、セカンドビザ（88日）の拠点になります。仕事・車・気候・生活のポイントをまとめました。",
    content: [
      "トゥーンバは内陸の地方都市、ガトンは周辺のロッキャーバレー（Lockyer Valley）にある農業地域。野菜を中心としたファーム求人があり、セカンドビザ（88日）を目指すワーホリの拠点になります。地方でののんびりした生活と、車社会に慣れる必要がある点が特徴です。",
      "ロッキャーバレーは野菜の主要産地として知られ、収穫やパッキングなどのファーム求人が季節で動きます。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。地域の詳しい情報は farm 系の地域ガイドも参照してください。",
      "トゥーンバの市街地にはバス網（Translink）がありますが、ファーム地域は公共交通が限られるため、車があると仕事・生活の選択肢が大きく広がります。トゥーンバは内陸の高台にあり、ブリスベンから車でアクセスするのが一般的です。",
      "内陸で寒暖差が大きく、冬（6〜8月）は朝晩が冷え込み霜が降りることもあります。夏は暑くなります（気候は BOM で確認）。防寒具と暑さ対策の両方を用意しましょう。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）内陸（Darling Downs／Lockyer Valley）" },
      { label: "特徴", value: "野菜のファーム地域・地方生活・車社会" },
      { label: "交通", value: "市街地はバス（Translink）／ファーム地域は車が必須級" },
      { label: "空港", value: "最寄りはトゥーンバ・ウェルキャンプ空港（WTB）。ブリスベン空港からのアクセスも一般的" },
      { label: "気候", value: "内陸・冬は冷え込み霜／夏は暑い" },
      { label: "向いている人", value: "ファームでセカンドビザ・地方生活・車移動OK" },
    ],
    steps: [
      { title: "車を確保", description: "ファーム地域は公共交通が限られるため、車があると仕事・生活の幅が大きく広がります。" },
      { title: "ファーム求人を探す", description: "Harvest Trail や地域の求人で収穫・パッキングを探し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "拠点を決める", description: "市街地（トゥーンバ）に住むか、ファームに近い地域に住むかを、仕事と生活のバランスで選びます。" },
    ],
    tips: [
      "内陸のため冬の冷え込み・霜と、夏の暑さの両方に備えましょう（気候は BOM で確認）。",
      "ファームは条件が農園ごとに異なります。悪質農園を避け、セカンドビザ対象作業かを事前に確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-gatton-lockyer", "area-brisbane", "area-overview", "farm-second-visa", "farm-finding", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a305",
    title: "バンダバーグ エリアガイド｜ファーム・家・交通",
    slug: "area-bundaberg",
    category: "area",
    hub: "area",
    description:
      "クイーンズランド州ワイドベイのバンダバーグ。サトウキビや野菜・果物のファーム地域で、セカンドビザ（88日）の拠点として人気です。仕事・住まい・交通・気候のポイントをまとめました。",
    content: [
      "バンダバーグはクイーンズランド州のワイドベイ地方にある地方都市で、サトウキビ・野菜・果物などのファームが広がる農業地域。セカンドビザ（88日）を目指すワーホリの定番拠点のひとつで、収穫・パッキングの仕事が季節で動きます。",
      "仕事は収穫やパッキングシェッドが中心で、作物のシーズンにより需要が変わります。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。悪質な農園・求人もあるため、条件・支払い方法・評判を確認します。",
      "ワーホリ向けのシェアハウスやバックパッカー宿があり、ファーム求人と住まいがセットで案内されることもあります。公共交通は限られるため、車や送迎の有無を確認しておくと安心です。空港はバンダバーグ空港（BDB）。",
      "温暖な亜熱帯気候で、夏は高温多湿。屋外作業が多いため、日焼け・熱中症対策と水分補給をしっかりと（気候は BOM で確認）。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）ワイドベイ" },
      { label: "特徴", value: "サトウキビ・野菜・果物のファーム地域・セカンドビザ拠点" },
      { label: "交通", value: "公共交通は限られる／車・送迎の確認を" },
      { label: "空港", value: "Bundaberg Airport（BDB）" },
      { label: "気候", value: "温暖な亜熱帯・夏は高温多湿" },
      { label: "向いている人", value: "ファームでセカンドビザ・地方生活" },
    ],
    steps: [
      { title: "ファーム求人を探す", description: "収穫・パッキングを求人や地域の情報で探し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "住まいを確保", description: "ワーホリ向けの宿やシェアハウスを探します。求人と住まいがセットの案内は条件をよく確認します。" },
      { title: "移動手段を確認", description: "公共交通が限られるため、車や農園の送迎の有無を確認しておきます。" },
    ],
    tips: [
      "悪質農園を避けるため、応募前に条件・支払い方法・評判と、セカンドビザ対象作業かを確認しましょう。",
      "屋外作業が多く夏は高温多湿です。日焼け・熱中症対策と水分補給をしっかりと（気候は BOM で確認）。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-bundaberg-farm", "area-overview", "farm-second-visa", "farm-finding", "second-visa-guide", "housing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a306",
    title: "スタンソープ エリアガイド｜寒さ・果樹・季節労働",
    slug: "area-stanthorpe",
    category: "area",
    hub: "area",
    description:
      "クイーンズランド州内陸のグラニットベルトにあるスタンソープ。りんご・ぶどうなどの果樹と野菜のファーム地域で、QLD の中でも寒さが特徴です。季節労働・気候・生活のポイントをまとめました。",
    content: [
      "スタンソープはクイーンズランド州内陸のグラニットベルト（Granite Belt）にある町で、りんご・ぶどう・野菜などの産地。収穫を中心とした季節労働があり、セカンドビザ（88日）の拠点になります。標高が高く、QLD の中では珍しく冬がしっかり寒いのが特徴です。",
      "果樹・野菜の収穫やパッキングの仕事が季節で動きます。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。屋外作業が中心のため、天候・体調管理も重要です。",
      "内陸の高地で寒暖差が大きく、冬（6〜8月）は冷え込みが強く霜や、まれに雪が降ることもあります。夏は日中暑くなります。防寒具をしっかり用意し、屋外作業では暑さ・UV 対策も両立させましょう（気候は BOM で確認）。",
      "公共交通は限られており、車があると仕事・生活の選択肢が広がります。最寄りの主要空港はブリスベンで、車での移動が基本です。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）内陸（Granite Belt）" },
      { label: "特徴", value: "りんご・ぶどう・野菜の産地・QLD で珍しく寒い" },
      { label: "交通", value: "公共交通は限られる／車が便利。主要空港はブリスベン" },
      { label: "気候", value: "高地・冬は冷え込み強く霜/まれに雪／夏は暑い" },
      { label: "向いている人", value: "果樹の季節労働・セカンドビザ・寒さOK" },
    ],
    steps: [
      { title: "車を確保", description: "公共交通が限られるため、車があると仕事・生活の幅が広がります。" },
      { title: "収穫シーズンに合わせて求人を探す", description: "果樹・野菜はシーズンが限られます。時期を確認し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "防寒準備", description: "冬は冷え込みが強いため、防寒具をしっかり用意します。屋外作業の暑さ・UV 対策も忘れずに。" },
    ],
    tips: [
      "QLD でも冬は冷え込みが強く霜が降ります。防寒対策を必ず用意しましょう（気候は BOM で確認）。",
      "ファームは農園ごとに条件が異なります。悪質農園を避け、セカンドビザ対象作業かを事前に確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Translink（QLD 公共交通・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値・低温/霜）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-stanthorpe-farm", "area-toowoomba-gatton", "area-overview", "farm-second-visa", "farm-work-clothing", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a307",
    title: "タウンズビル エリアガイド｜北QLDの仕事と暮らし",
    slug: "area-townsville",
    category: "area",
    hub: "area",
    description:
      "熱帯クイーンズランド北部の都市タウンズビル。観光・医療・建設などの仕事があり、周辺のファーム地域への拠点にもなります。交通・気候・空港をワーホリ目線でまとめました。",
    content: [
      "タウンズビルはクイーンズランド州北部（North QLD）にある都市で、ケアンズより南の熱帯エリア。観光・ホスピタリティに加え、医療・建設など都市機能があり、周辺の農業地域（ボウエン・エアーなど）への拠点にもなります。熱帯の都市で働きたい・暮らしたいワーホリに向いています。",
      "仕事は観光・飲食・小売のほか、都市規模がある分、清掃・建設などもあります。周辺のファーム地域はセカンドビザ対象の収穫作業があり、時期により需要が動きます。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。",
      "公共交通は路線バス（Sunbus）が中心で、Translink の go card（タッチ決済対応）で乗車します。鉄道・トラムはありません。周辺地域やファームへは車があると便利です。空港はタウンズビル空港（TSV）。",
      "熱帯乾燥気候で、1年を通じて暖かく晴天が多め。雨季（おおむね11〜4月）は蒸し暑く、サイクロンの可能性もあります。BOM の気象・警報を確認しましょう。UV も強いので日焼け対策を。",
    ],
    keyFacts: [
      { label: "州", value: "クイーンズランド州（QLD）北部（North QLD）" },
      { label: "特徴", value: "熱帯の都市・観光/医療/建設・周辺ファーム拠点" },
      { label: "交通", value: "路線バス（Sunbus）／Translink go card。周辺は車が便利" },
      { label: "空港", value: "Townsville Airport（TSV）" },
      { label: "気候", value: "熱帯乾燥・雨季（11〜4月頃）・サイクロン注意" },
      { label: "向いている人", value: "熱帯の都市で働きたい・周辺ファームの拠点にしたい" },
    ],
    steps: [
      { title: "go card を用意", description: "QLD の公共交通は Translink の go card（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "仕事を探す", description: "都市の観光・飲食・清掃・建設に加え、周辺ファームの収穫も視野に入れます。セカンドビザ狙いは対象作業・地域を確認します。" },
      { title: "移動手段を確保", description: "周辺地域やファームへは車があると仕事・生活の幅が広がります。" },
    ],
    tips: [
      "雨季（11〜4月頃）は蒸し暑く、サイクロンの可能性もあります。BOM の気象・警報を確認しましょう。",
      "セカンドビザ狙いは、雇用主が対象作業・対象地域かを事前に確認し、悪質な求人には注意しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Translink（QLD 公共交通・go card・運賃）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Townsville Airport（TSV・空港アクセス）", url: "https://www.townsvilleairport.com.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages・気象警報", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-cairns", "area-overview", "region-bowen-ayr-farm", "farm-second-visa", "jobs-guide", "housing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a308",
    title: "ニューカッスル エリアガイド｜シドニー外の仕事と家賃",
    slug: "area-newcastle",
    category: "area",
    hub: "area",
    description:
      "ニューサウスウェールズ州の沿岸都市ニューカッスル。シドニーの北にあり、シドニーより家賃を抑えつつ都市生活を送れます。仕事・交通・気候・空港をまとめました。",
    content: [
      "ニューカッスルはニューサウスウェールズ州（NSW）の沿岸都市で、シドニーの北。NSW 有数の都市圏として都市機能がありながら、シドニーより家賃を抑えやすいのが魅力です。ビーチも近く、シドニー以外の NSW の拠点を探すワーホリに向いています。",
      "仕事は飲食・小売・ホスピタリティ・清掃などがあります。港湾・産業都市としての側面もあります。求人はシドニーより少なめのため、求人サイト・店頭応募など複数の探し方を併用しましょう。",
      "公共交通は Transport for NSW の電車・バス・ライトレール・フェリーが使え、Opal カード（タッチ決済対応）で乗車します。シドニーとは電車でつながっています。空港はニューカッスル空港（NTL）。",
      "温暖な気候で四季の変化は穏やか。夏は UV が強いので日焼け対策を（BOM で確認）。家賃はシドニーより抑えやすい傾向ですが、エリア・時期で変動するため、最新は Flatmates・realestate.com.au で確認しましょう。",
    ],
    keyFacts: [
      { label: "州", value: "ニューサウスウェールズ州（NSW）沿岸（シドニーの北）" },
      { label: "特徴", value: "都市機能＋シドニーより家賃控えめ・ビーチが近い" },
      { label: "交通", value: "Transport for NSW（電車/バス/ライトレール/フェリー）／Opal" },
      { label: "空港", value: "Newcastle Airport（NTL）" },
      { label: "家賃", value: "変動。最新は Flatmates・realestate.com.au で確認" },
      { label: "向いている人", value: "シドニー以外の NSW 拠点・都市生活" },
    ],
    steps: [
      { title: "Opal を用意", description: "NSW の公共交通は Opal カード（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "エリアを選ぶ", description: "電車・バス沿線でシェアハウスを探すと通勤しやすくなります。" },
      { title: "仕事を複数の方法で探す", description: "求人がシドニーより少なめのため、求人サイトと店頭応募を併用します。" },
    ],
    tips: [
      "シドニーへは電車で移動できるため、都市部の求人も視野に入れられます。",
      "求人が大都市より少なめなので、探し方を複数持つと安心です。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Transport for NSW（NSW 公共交通・Opal・運賃）", url: "https://transportnsw.info/", accessedAt: "2026-07-30" },
      { label: "Newcastle Airport（NTL・空港アクセス）", url: "https://www.newcastleairport.com.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-sydney", "area-overview", "jobs-guide", "housing-guide", "transport-payment-guide", "clothing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a309",
    title: "ウーロンゴン エリアガイド｜大学・ビーチ・通勤",
    slug: "area-wollongong",
    category: "area",
    hub: "area",
    description:
      "ニューサウスウェールズ州の沿岸都市ウーロンゴン。シドニーの南にある大学とビーチの街で、シドニーへの通勤圏でもあります。仕事・交通・気候をまとめました。",
    content: [
      "ウーロンゴンはニューサウスウェールズ州（NSW）の沿岸都市で、シドニーの南。大学のある街でビーチが近く、シドニーへ電車で通える距離にあります。落ち着いた沿岸都市で暮らしたいワーホリや、シドニー圏で家賃を抑えたい人に向いています。",
      "仕事は飲食・小売・ホスピタリティ・清掃などがあります。学生の街のためカフェ・飲食の需要がありますが、求人はシドニーより少なめのため、複数の探し方を併用しましょう。",
      "公共交通は Transport for NSW の電車・バスが中心で、Opal カード（タッチ決済対応）で乗車します。シドニーとは電車でつながっています。海沿いに広がるため、エリアによっては車があると便利です。",
      "温暖な気候で、夏は UV が強いので日焼け対策を（BOM で確認）。家賃はエリア・時期で変動するため、最新は Flatmates・realestate.com.au で確認しましょう。",
    ],
    keyFacts: [
      { label: "州", value: "ニューサウスウェールズ州（NSW）沿岸（シドニーの南）" },
      { label: "特徴", value: "大学・ビーチ・シドニー通勤圏" },
      { label: "交通", value: "Transport for NSW（電車/バス）／Opal。エリアにより車が便利" },
      { label: "空港", value: "最寄りはシドニー空港" },
      { label: "家賃", value: "変動。最新は Flatmates・realestate.com.au で確認" },
      { label: "向いている人", value: "沿岸都市の生活・シドニー圏で家賃控えめ" },
    ],
    steps: [
      { title: "Opal を用意", description: "NSW の公共交通は Opal カード（対応クレカ/スマホのタッチも可）で利用します。" },
      { title: "エリアを選ぶ", description: "電車沿線や海沿いなど、通勤とライフスタイルに合わせてエリアを絞ります。" },
      { title: "飲食・接客求人を探す", description: "学生の街でカフェ・飲食の需要があります。求人サイトと店頭応募を併用します。" },
    ],
    tips: [
      "シドニーへ電車で通勤でき、都市部の求人も視野に入れられます。",
      "学生の街のためカフェ・飲食の需要がありますが、求人数は大都市より少なめです。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Transport for NSW（NSW 公共交通・Opal・運賃）", url: "https://transportnsw.info/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-sydney", "area-newcastle", "area-overview", "jobs-guide", "housing-guide", "clothing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a310",
    title: "ミルデューラ エリアガイド｜ファームと地方生活",
    slug: "area-mildura",
    category: "area",
    hub: "area",
    description:
      "ビクトリア州北西部、マレー川沿いのミルデューラ。ぶどう・柑橘・アーモンドなどのファーム地域で、セカンドビザ（88日）の拠点になります。仕事・交通・気候・生活をまとめました。",
    content: [
      "ミルデューラはビクトリア州（VIC）北西部、マレー川（Murray River）沿いにある地方都市。ぶどう（ドライフルーツ）・柑橘・アーモンドなどのファームが広がり、セカンドビザ（88日）を目指すワーホリの定番拠点のひとつです。乾燥した内陸で日照が多く、収穫の仕事が季節で動きます。",
      "仕事は収穫やパッキングが中心で、作物のシーズンにより需要が変わります。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。悪質な農園・求人もあるため、条件・支払い方法・評判を確認します。",
      "地方都市のため公共交通は限られ、V/Line の鉄道・コーチ（長距離バス）や地域バスが使えます（運行は Public Transport Victoria で確認）。ファーム地域へ通うには車があると便利です。空港はミルデューラ空港（MQL）。",
      "乾燥した内陸気候で、夏は高温になり屋外作業は暑さ対策が重要です。冬は朝晩冷え込みます。日焼け・熱中症対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    keyFacts: [
      { label: "州", value: "ビクトリア州（VIC）北西部（マレー川沿い）" },
      { label: "特徴", value: "ぶどう/柑橘/アーモンドのファーム・セカンドビザ拠点" },
      { label: "交通", value: "V/Line・地域バス（PTV）／ファームは車が便利" },
      { label: "空港", value: "Mildura Airport（MQL）" },
      { label: "気候", value: "乾燥内陸・夏は高温／冬は朝晩冷え込み" },
      { label: "向いている人", value: "ファームでセカンドビザ・地方生活" },
    ],
    steps: [
      { title: "車を確保", description: "ファーム地域は公共交通が限られるため、車があると仕事・生活の幅が広がります。" },
      { title: "ファーム求人を探す", description: "収穫・パッキングを求人や地域の情報で探し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "住まいを確保", description: "ワーホリ向けの宿やシェアハウスを探します。求人と住まいがセットの案内は条件をよく確認します。" },
    ],
    tips: [
      "悪質農園を避けるため、応募前に条件・支払い方法・評判と、セカンドビザ対象作業かを確認しましょう。",
      "夏は高温で屋外作業がきびしく、冬は冷え込みます。暑さ・UV 対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Public Transport Victoria（VIC 公共交通・V/Line・運賃）", url: "https://www.ptv.vic.gov.au/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-mildura-farm", "area-overview", "farm-second-visa", "farm-finding", "second-visa-guide", "housing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },

  {
    id: "a311",
    title: "シェパートン エリアガイド｜農業地域での生活",
    slug: "area-shepparton",
    category: "area",
    hub: "area",
    description:
      "ビクトリア州北部、ゴールバーンバレーのシェパートン。果物や野菜のファームと食品加工で知られる農業地域で、セカンドビザ（88日）の拠点になります。仕事・交通・気候をまとめました。",
    content: [
      "シェパートンはビクトリア州（VIC）北部、ゴールバーンバレー（Goulburn Valley）にある地方都市。梨・りんご・トマトなどの果物・野菜のファームと食品加工（フルーツ缶詰など）で知られる農業地域で、セカンドビザ（88日）を目指すワーホリの拠点になります。",
      "仕事は収穫やパッキング、食品加工などが季節で動きます。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。悪質な農園・求人もあるため、条件・支払い方法・評判を確認します。",
      "公共交通は V/Line の鉄道と地域バスが使えます（運行は Public Transport Victoria で確認）。メルボルンとは鉄道でつながっています。ファーム地域へ通うには車があると便利です。",
      "内陸で寒暖差があり、夏は高温、冬は朝晩冷え込みます。屋外作業が多いため、暑さ・UV 対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    keyFacts: [
      { label: "州", value: "ビクトリア州（VIC）北部（ゴールバーンバレー）" },
      { label: "特徴", value: "果物/野菜のファーム・食品加工・セカンドビザ拠点" },
      { label: "交通", value: "V/Line（鉄道）・地域バス（PTV）／ファームは車が便利" },
      { label: "空港", value: "最寄りはメルボルン" },
      { label: "気候", value: "内陸・夏は高温／冬は朝晩冷え込み" },
      { label: "向いている人", value: "ファーム・食品加工でセカンドビザ" },
    ],
    steps: [
      { title: "ファーム・加工求人を探す", description: "収穫・パッキング・食品加工を求人や地域の情報で探し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "住まいを確保", description: "ワーホリ向けの宿やシェアハウスを探します。求人と住まいがセットの案内は条件をよく確認します。" },
      { title: "移動手段を確認", description: "ファーム地域へ通うには車や送迎の有無を確認しておくと安心です。" },
    ],
    tips: [
      "悪質農園を避けるため、応募前に条件・支払い方法・評判と、セカンドビザ対象作業かを確認しましょう。",
      "夏は高温、冬は冷え込みます。暑さ・UV 対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Public Transport Victoria（VIC 公共交通・V/Line・運賃）", url: "https://www.ptv.vic.gov.au/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-shepparton-farm", "area-mildura", "area-overview", "farm-second-visa", "farm-finding", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a312",
    title: "グリフィス エリアガイド｜農業・食品加工・生活",
    slug: "area-griffith",
    category: "area",
    hub: "area",
    description:
      "ニューサウスウェールズ州内陸のグリフィス。かんきつ・ぶどう・野菜などの農業と食品加工で知られる地域で、セカンドビザ（88日）の拠点になります。仕事・交通・気候をまとめました。",
    content: [
      "グリフィスはニューサウスウェールズ州（NSW）内陸のリベリーナ（Riverina）地方にある地方都市。かんきつ・ぶどう・野菜などの農業と、ワイナリーや食品加工で知られ、セカンドビザ（88日）を目指すワーホリの拠点になります。",
      "仕事は収穫やパッキング、食品加工などが季節で動きます。セカンドビザを狙う場合は、雇用主が対象作業・対象地域かを事前に確認しましょう。悪質な農園・求人もあるため、条件・支払い方法・評判を確認します。",
      "地方都市のため公共交通は限られ、車があると仕事・生活の選択肢が広がります。長距離の移動は NSW TrainLink のコーチ・鉄道が使えます（運行は Transport for NSW で確認）。",
      "乾燥した内陸気候で、夏は高温、冬は朝晩冷え込みます。屋外作業が多いため、暑さ・UV 対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    keyFacts: [
      { label: "州", value: "ニューサウスウェールズ州（NSW）内陸（リベリーナ）" },
      { label: "特徴", value: "かんきつ/ぶどう/野菜のファーム・食品加工・セカンドビザ拠点" },
      { label: "交通", value: "車が便利／長距離は NSW TrainLink（コーチ・鉄道）" },
      { label: "気候", value: "乾燥した内陸・夏は高温／冬は朝晩冷え込み" },
      { label: "向いている人", value: "ファーム・食品加工でセカンドビザ" },
    ],
    steps: [
      { title: "移動手段を確保", description: "車があると仕事・生活の選択肢が広がります。長距離移動は NSW TrainLink の運行を確認します。" },
      { title: "ファーム・加工求人を探す", description: "収穫・パッキング・食品加工を求人や地域の情報で探し、雇用主が対象作業・対象地域かを確認します。" },
      { title: "住まいを確保", description: "ワーホリ向けの宿やシェアハウスを探します。求人と住まいがセットの案内は条件をよく確認します。" },
    ],
    tips: [
      "悪質農園を避けるため、応募前に条件・支払い方法・評判と、セカンドビザ対象作業かを確認しましょう。",
      "夏は高温、冬は冷え込みます。暑さ・UV 対策と防寒の両方を用意しましょう（気候は BOM で確認）。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Transport for NSW（NSW 交通・NSW TrainLink）", url: "https://transportnsw.info/", accessedAt: "2026-07-30" },
      { label: "Department of Home Affairs｜Specified work（417 セカンドビザ対象作業）", url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/specified-work", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["region-griffith-farm", "area-mildura", "area-overview", "farm-second-visa", "farm-finding", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a313",
    title: "ニューサウスウェールズ州ガイド｜制度・都市・仕事",
    slug: "state-nsw-guide",
    category: "area",
    hub: "area",
    description:
      "オーストラリア最大の人口を持つニューサウスウェールズ州（NSW）。シドニーを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・仕事をワーホリ目線でまとめた州ガイドです。",
    content: [
      "ニューサウスウェールズ州（NSW）はオーストラリア最大の人口を持つ州で、州都はシドニー。仕事の数が多く、初めてのワーホリにも人気です。この記事では NSW の制度（免許・賃貸・交通）の要点と、都市の選び方をまとめます。",
      "公共交通は Transport for NSW の Opal カードで、シドニー都市圏の電車・バス・ライトレール・フェリーを利用できます。運転免許の切替や車の登録（Rego）などの手続きは Service NSW で行います。賃貸・ボンド（敷金）のルールは NSW Fair Trading が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "シドニーは求人が多く、ジャパレスからローカルまで選択肢が豊富です。地方（Regional NSW）では農業などセカンドビザ対象の仕事が見つかることもあります。",
      "都市生活ならシドニー、家賃を抑えたいならニューカッスル、大学・ビーチと通勤圏ならウーロンゴン、内陸のファームならグリフィスなど。各都市の詳細は専用ガイドを参照してください。",
    ],
    keyFacts: [
      { label: "州都", value: "シドニー" },
      { label: "交通", value: "Transport for NSW（Opal カード）" },
      { label: "免許・登録", value: "Service NSW" },
      { label: "賃貸・ボンド", value: "NSW Fair Trading" },
      { label: "主な都市", value: "シドニー／ニューカッスル／ウーロンゴン／グリフィス" },
      { label: "向いている人", value: "仕事の多い州で働きたい" },
    ],
    steps: [
      { title: "都市を選ぶ", description: "生活スタイルと予算に合わせて、シドニー・ニューカッスル・ウーロンゴン・グリフィスなどから拠点を選びます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（Service NSW）、賃貸・ボンド（NSW Fair Trading）、交通（Opal）の要点を確認します。" },
      { title: "仕事を探す", description: "都市はローカル・ジャパレス、地方はセカンドビザ対象の農業などを視野に探します。" },
    ],
    tips: [
      "免許の切替ルールや賃貸の条件は変わることがあります。手続き前に各公式で最新を確認しましょう。",
      "地方（Regional NSW）ではセカンドビザ対象の仕事が見つかることもあります。対象作業・地域を確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Service NSW（運転免許・車の登録など州の手続き）", url: "https://www.service.nsw.gov.au/", accessedAt: "2026-07-30" },
      { label: "Transport for NSW（NSW 公共交通・Opal）", url: "https://transportnsw.info/", accessedAt: "2026-07-30" },
      { label: "NSW Fair Trading（賃貸・ボンド・テナンシー）", url: "https://www.fairtrading.nsw.gov.au/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-sydney", "area-newcastle", "area-wollongong", "area-overview", "housing-guide", "license-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a314",
    title: "ビクトリア州ガイド｜制度・都市・仕事",
    slug: "state-vic-guide",
    category: "area",
    hub: "area",
    description:
      "南東部の州ビクトリア（VIC）。メルボルンを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・仕事・ファームをワーホリ目線でまとめた州ガイドです。",
    content: [
      "ビクトリア州（VIC）はオーストラリア南東部の州で、州都はメルボルン。文化・カフェ・イベントが盛んな都市で、仕事の選択肢も豊富です。この記事では VIC の制度（免許・賃貸・交通）の要点と、都市・ファームの選び方をまとめます。",
      "公共交通はメルボルン都市圏で myki カードを使い、電車・トラム・バスを利用できます（運行・運賃は Public Transport Victoria で確認）。運転免許の切替や車の登録は VicRoads が所管します。賃貸・ボンドのルールは Consumer Affairs Victoria が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "メルボルンは求人が多く、ローカル・ジャパレスとも選択肢が豊富です。州北部のミルデューラ・シェパートンなどはファーム・食品加工が盛んで、セカンドビザ対象の仕事が季節で動きます。",
      "都市生活ならメルボルン、ぶどう・かんきつのファームならミルデューラ、果物・食品加工ならシェパートンなど。各地域の詳細は専用ガイドを参照してください。",
    ],
    keyFacts: [
      { label: "州都", value: "メルボルン" },
      { label: "交通", value: "Public Transport Victoria（myki カード）" },
      { label: "免許・登録", value: "VicRoads" },
      { label: "賃貸・ボンド", value: "Consumer Affairs Victoria" },
      { label: "主な地域", value: "メルボルン／ミルデューラ／シェパートン" },
      { label: "向いている人", value: "都市生活・ファームの両方" },
    ],
    steps: [
      { title: "都市・地域を選ぶ", description: "都市生活ならメルボルン、ファームなら北部のミルデューラ・シェパートンなどから拠点を選びます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（VicRoads）、賃貸・ボンド（Consumer Affairs Victoria）、交通（myki）の要点を確認します。" },
      { title: "仕事を探す", description: "都市はローカル・ジャパレス、北部はセカンドビザ対象のファーム・食品加工を視野に探します。" },
    ],
    tips: [
      "免許の切替ルールや賃貸の条件は変わることがあります。手続き前に各公式で最新を確認しましょう。",
      "州北部（ミルデューラ・シェパートンなど）はファーム・食品加工が盛んで、セカンドビザ対象の仕事が季節で動きます。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "VicRoads（運転免許・車の登録）", url: "https://www.vicroads.vic.gov.au/", accessedAt: "2026-07-30" },
      { label: "Public Transport Victoria（VIC 公共交通・myki）", url: "https://www.ptv.vic.gov.au/", accessedAt: "2026-07-30" },
      { label: "Consumer Affairs Victoria（賃貸・ボンド・テナンシー）", url: "https://www.consumer.vic.gov.au/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-melbourne", "area-mildura", "area-shepparton", "area-overview", "housing-guide", "license-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a315",
    title: "クイーンズランド州ガイド｜制度・都市・ファーム",
    slug: "state-qld-guide",
    category: "area",
    hub: "area",
    description:
      "温暖な北東部の州クイーンズランド（QLD）。ブリスベンを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・観光・ファームをワーホリ目線でまとめた州ガイドです。",
    content: [
      "クイーンズランド州（QLD）はオーストラリア北東部の温暖な州で、州都はブリスベン。ビーチ・観光と、熱帯・亜熱帯のファームが充実し、セカンドビザ拠点としても人気です。この記事では QLD の制度（免許・賃貸・交通）の要点と、都市・ファームの選び方をまとめます。",
      "公共交通は Translink の go card で、ブリスベン都市圏や各地の電車・バス・フェリーを利用できます。運転免許の切替や車の登録は Queensland Government（Transport and motoring）で手続きします。賃貸・ボンドのルールは Residential Tenancies Authority（RTA）が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "ブリスベン・ゴールドコースト・サンシャインコーストは観光・接客の仕事が中心。ケアンズ・タウンズビル・バンダバーグ・スタンソープ・トゥーンバ/ガトンなどはファームが盛んで、セカンドビザ対象の仕事が季節で動きます。",
      "都市生活ならブリスベン、ビーチと観光ならゴールドコースト／サンシャインコースト、熱帯・ファームならケアンズ／タウンズビル、内陸・寒冷な果樹ならスタンソープなど。各地域の詳細は専用ガイドを参照してください。",
    ],
    keyFacts: [
      { label: "州都", value: "ブリスベン" },
      { label: "交通", value: "Translink（go card）" },
      { label: "免許・登録", value: "Queensland Government（Transport and motoring）" },
      { label: "賃貸・ボンド", value: "Residential Tenancies Authority（RTA）" },
      { label: "主な地域", value: "ブリスベン／ゴールドコースト／ケアンズ／バンダバーグ ほか" },
      { label: "向いている人", value: "温暖な気候・観光・ファーム" },
    ],
    steps: [
      { title: "都市・地域を選ぶ", description: "都市生活はブリスベン、観光はゴールドコースト、ファームはケアンズ・バンダバーグなどから拠点を選びます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（Transport and motoring）、賃貸・ボンド（RTA）、交通（go card）の要点を確認します。" },
      { title: "仕事を探す", description: "都市は観光・接客、地方はセカンドビザ対象のファームを視野に探します。" },
    ],
    tips: [
      "熱帯・亜熱帯では雨季・サイクロンに注意。天候と警報を確認しましょう。",
      "ファームでセカンドビザを狙う場合は、対象作業・対象地域かを事前に確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Queensland Government｜Transport and motoring（運転免許・車の登録）", url: "https://www.qld.gov.au/transport", accessedAt: "2026-07-30" },
      { label: "Translink（QLD 公共交通・go card）", url: "https://translink.com.au/", accessedAt: "2026-07-30" },
      { label: "Residential Tenancies Authority（RTA・賃貸・ボンド）", url: "https://www.rta.qld.gov.au/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-brisbane", "area-gold-coast", "area-cairns", "area-overview", "farm-second-visa", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a316",
    title: "西オーストラリア州ガイド｜制度・都市・地方移動",
    slug: "state-wa-guide",
    category: "area",
    hub: "area",
    description:
      "国土の広い範囲を占める西オーストラリア州（WA）。パースを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・地方移動・仕事をワーホリ目線でまとめた州ガイドです。",
    content: [
      "西オーストラリア州（WA）はオーストラリアの西側、国土の広い範囲を占める州で、州都はパース。東海岸から離れた独立した大都市圏で、晴天と西海岸の暮らしが魅力です。この記事では WA の制度（免許・賃貸・交通）の要点と、都市・地方移動の考え方をまとめます。",
      "公共交通はパース都市圏で Transperth の SmartRider を使い、電車・バス・フェリーを利用できます。運転免許の切替や車の登録は Department of Transport（WA）で手続きします。賃貸・ボンドのルールは Consumer Protection（WA）が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "パースはホスピタリティ・小売・建設などの仕事があります。WA は広大で、地方（Regional WA）はセカンドビザ対象の農業などがありますが、都市間の距離が非常に長いため、移動計画（車・長距離バス・国内線）を立てておくことが重要です。東海岸との時差（AWST）にも注意しましょう。",
      "拠点は基本的にパース。地方で働く場合は距離と移動手段をよく確認してから動きましょう。パースの詳細は専用ガイドを参照してください。",
    ],
    keyFacts: [
      { label: "州都", value: "パース" },
      { label: "交通", value: "Transperth（SmartRider）" },
      { label: "免許・登録", value: "Department of Transport（WA）" },
      { label: "賃貸・ボンド", value: "Consumer Protection（WA）" },
      { label: "特徴", value: "広大・都市間の距離が長い・東海岸との時差（AWST）" },
      { label: "向いている人", value: "西海岸の都市生活・地方移動OK" },
    ],
    steps: [
      { title: "パースを拠点にする", description: "まずはパースを拠点に、仕事・住まい・交通（SmartRider）を整えます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（Department of Transport WA）、賃貸・ボンド（Consumer Protection WA）の要点を確認します。" },
      { title: "地方移動を計画", description: "地方で働く場合は都市間の距離が長いため、車・長距離バス・国内線などの移動計画を立てます。" },
    ],
    tips: [
      "WA は広大で都市間の距離が非常に長いです。地方へ動く前に移動手段と費用を確認しましょう。",
      "東海岸との時差（AWST）があります。連絡や予約の時間に注意しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Department of Transport（WA・運転免許・車の登録）", url: "https://www.transport.wa.gov.au/", accessedAt: "2026-07-30" },
      { label: "Transperth（WA 公共交通・SmartRider）", url: "https://www.transperth.wa.gov.au/", accessedAt: "2026-07-30" },
      { label: "Consumer Protection（WA・賃貸・ボンド・テナンシー）", url: "https://www.commerce.wa.gov.au/consumer-protection", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-perth", "area-overview", "housing-guide", "license-guide", "jobs-guide", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a317",
    title: "南オーストラリア州ガイド｜制度・都市・農業",
    slug: "state-sa-guide",
    category: "area",
    hub: "area",
    description:
      "落ち着いた南部の州、南オーストラリア（SA）。アデレードを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・農業・ワインをワーホリ目線でまとめた州ガイドです。",
    content: [
      "南オーストラリア州（SA）はオーストラリア南部の州で、州都はアデレード。物価や家賃が比較的落ち着いているとされ、ワインの産地（バロッサ・バレー等）や農業でも知られます。この記事では SA の制度（免許・賃貸・交通）の要点と、都市・農業の選び方をまとめます。",
      "公共交通はアデレード都市圏で Adelaide Metro の metroCARD を使い、電車・トラム・バスを利用できます。運転免許の切替や車の登録は Service SA（mySA GOV）で手続きします。賃貸・ボンドのルールは Consumer and Business Services（CBS）が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "アデレードはローカル・ジャパレスの仕事があります。州内の地方（Regional SA）ではぶどう・野菜などの農業があり、セカンドビザ対象の仕事が季節で動きます。対象作業・対象地域かを事前に確認しましょう。",
      "都市生活ならアデレード、農業・ワインの地方で働くなら距離と移動手段を確認してから動きましょう。地方は車があると選択肢が広がります。",
    ],
    keyFacts: [
      { label: "州都", value: "アデレード" },
      { label: "交通", value: "Adelaide Metro（metroCARD）" },
      { label: "免許・登録", value: "Service SA（mySA GOV）" },
      { label: "賃貸・ボンド", value: "Consumer and Business Services（CBS）" },
      { label: "特徴", value: "物価が落ち着いた傾向・ワイン産地・農業" },
      { label: "向いている人", value: "落ち着いた都市生活・農業でセカンドビザ" },
    ],
    steps: [
      { title: "都市・地域を選ぶ", description: "都市生活はアデレード、農業なら地方（Regional SA）から拠点を選びます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（Service SA）、賃貸・ボンド（CBS）、交通（metroCARD）の要点を確認します。" },
      { title: "仕事を探す", description: "都市はローカル・ジャパレス、地方はセカンドビザ対象の農業を視野に探します。" },
    ],
    tips: [
      "免許の切替ルールや賃貸の条件は変わることがあります。手続き前に各公式で最新を確認しましょう。",
      "地方（Regional SA）でセカンドビザを狙う場合は、対象作業・対象地域かを事前に確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Service SA / mySA GOV（運転免許・車の登録）", url: "https://www.sa.gov.au/topics/driving-and-transport", accessedAt: "2026-07-30" },
      { label: "Adelaide Metro（SA 公共交通・metroCARD）", url: "https://www.adelaidemetro.com.au/", accessedAt: "2026-07-30" },
      { label: "Consumer and Business Services（CBS・賃貸・ボンド）", url: "https://www.cbs.sa.gov.au/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-adelaide", "area-overview", "housing-guide", "license-guide", "farm-second-visa", "second-visa-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a318",
    title: "タスマニア州ガイド｜制度・都市・ファーム",
    slug: "state-tas-guide",
    category: "area",
    hub: "area",
    description:
      "島の州タスマニア（TAS）。ホバートを中心に、免許・賃貸・公共交通などの州の制度と、都市の選び方・ファーム・寒さ対策をワーホリ目線でまとめた州ガイドです。",
    content: [
      "タスマニア州（TAS）はオーストラリア本土の南に浮かぶ島の州で、州都はホバート。自然が豊かで、果物・野菜のファームや水産・観光の仕事があり、セカンドビザ拠点としても知られます。この記事では TAS の制度（免許・賃貸・交通）の要点と、都市・ファームの選び方をまとめます。",
      "公共交通はホバートやローンセストンで Metro Tasmania のバス（greencard）などが使えますが、本土の大都市より路線は限られます。運転免許の切替や車の登録は Transport Tasmania（Service Tasmania）で手続きします。賃貸・ボンドのルールは Consumer, Building and Occupational Services（CBOS）が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "ホバート・ローンセストンはローカル・観光の仕事があります。州内の地方ではベリー・りんご・さくらんぼなどのファームがあり、セカンドビザ対象の仕事が季節で動きます。対象作業・対象地域かを事前に確認しましょう。",
      "他州より涼しく、冬は冷え込みます。屋外作業や観光の仕事では防寒をしっかり用意しましょう（気候は BOM で確認）。地方は車があると移動の選択肢が広がります。",
    ],
    keyFacts: [
      { label: "州都", value: "ホバート" },
      { label: "交通", value: "Metro Tasmania（greencard・バス）／路線は限定的" },
      { label: "免許・登録", value: "Transport Tasmania（Service Tasmania）" },
      { label: "賃貸・ボンド", value: "Consumer, Building and Occupational Services（CBOS）" },
      { label: "気候", value: "他州より涼しい・冬は冷え込み" },
      { label: "向いている人", value: "自然・ファームでセカンドビザ・涼しい気候" },
    ],
    steps: [
      { title: "都市・地域を選ぶ", description: "都市生活はホバート・ローンセストン、ファームなら地方から拠点を選びます。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（Service Tasmania）、賃貸・ボンド（CBOS）、交通（greencard）の要点を確認します。" },
      { title: "仕事を探す", description: "都市はローカル・観光、地方はセカンドビザ対象のベリー・果樹などを視野に探します。" },
    ],
    tips: [
      "他州より涼しく冬は冷え込みます。防寒を用意しましょう（気候は BOM で確認）。",
      "地方のファームでセカンドビザを狙う場合は、対象作業・対象地域かを事前に確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Transport Tasmania / Service Tasmania（運転免許・車の登録）", url: "https://www.transport.tas.gov.au/", accessedAt: "2026-07-30" },
      { label: "Metro Tasmania（TAS 公共交通・greencard）", url: "https://www.metrotas.com.au/", accessedAt: "2026-07-30" },
      { label: "Consumer, Building and Occupational Services（CBOS・賃貸・ボンド）", url: "https://www.cbos.tas.gov.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages（気候平年値）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-hobart", "region-tasmania-farm", "area-overview", "farm-second-visa", "second-visa-guide", "housing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
  {
    id: "a319",
    title: "ノーザンテリトリーガイド｜気候・仕事・安全",
    slug: "state-nt-guide",
    category: "area",
    hub: "area",
    description:
      "熱帯の準州ノーザンテリトリー（NT）。ダーウィンを中心に、免許・賃貸・公共交通などの制度と、乾季・雨季の気候・仕事・安全対策をワーホリ目線でまとめた準州ガイドです。",
    content: [
      "ノーザンテリトリー（NT）はオーストラリア北部の準州で、主要都市はダーウィン、内陸にはアリススプリングスがあります。熱帯・砂漠の気候で、乾季・雨季がはっきり分かれ、季節労働や観光の仕事があります。この記事では NT の制度（免許・賃貸・交通）の要点と、気候・安全の考え方をまとめます。",
      "公共交通はダーウィン都市圏で路線バスなどが使えますが、本土の大都市より限られます。運転免許の切替や車の登録は Northern Territory Government（MVR）で手続きします。賃貸・ボンドのルールは NT Consumer Affairs が所管します。滞在者の免許ルールや賃貸の条件は変わることがあるため、最新は各公式で確認しましょう。",
      "ダーウィンはホスピタリティ・観光の仕事があり、周辺では季節労働（マンゴー等）でセカンドビザ対象の仕事が動きます。対象作業・対象地域かを事前に確認しましょう。都市間が非常に遠いため、移動計画（車・長距離バス・国内線）を立てておくことが重要です。",
      "熱帯で、乾季（5〜10月頃）は過ごしやすく、雨季（11〜4月頃）は高温多湿でサイクロンや洪水のリスクがあります。暑さ・UV 対策と、雨季の気象警報の確認を習慣にしましょう（気候・警報は BOM で確認）。屋外や remote な場所では安全対策も重要です。",
    ],
    keyFacts: [
      { label: "主要都市", value: "ダーウィン／アリススプリングス（内陸）" },
      { label: "交通", value: "路線バス（都市圏）／都市間は車・長距離バス・国内線" },
      { label: "免許・登録", value: "Northern Territory Government（MVR）" },
      { label: "賃貸・ボンド", value: "NT Consumer Affairs" },
      { label: "気候", value: "熱帯・乾季/雨季・サイクロン注意" },
      { label: "向いている人", value: "熱帯の季節労働・観光・移動OK" },
    ],
    steps: [
      { title: "都市・地域を選ぶ", description: "拠点はダーウィンが中心。内陸のアリススプリングスなどは距離と移動手段を確認します。" },
      { title: "制度手続きを確認", description: "免許の切替・車の登録（NT Government MVR）、賃貸・ボンド（NT Consumer Affairs）の要点を確認します。" },
      { title: "気候・安全に備える", description: "乾季/雨季の違い、雨季のサイクロン・洪水の警報確認、暑さ・UV 対策を準備します。" },
    ],
    tips: [
      "雨季（11〜4月頃）は高温多湿でサイクロン・洪水のリスク。気象警報を確認しましょう（BOM）。",
      "都市間が非常に遠いです。移動手段と費用、remote な場所での安全対策を確認しましょう。",
    ],
    verifiedAt: "2026-07-30",
    officialSources: [
      { label: "Northern Territory Government｜MVR（運転免許・車の登録）", url: "https://nt.gov.au/driving", accessedAt: "2026-07-30" },
      { label: "Northern Territory Government｜Public transport（NT 公共交通）", url: "https://nt.gov.au/driving/public-transport-cycling", accessedAt: "2026-07-30" },
      { label: "NT Consumer Affairs（賃貸・ボンド・テナンシー）", url: "https://consumeraffairs.nt.gov.au/", accessedAt: "2026-07-30" },
      { label: "Bureau of Meteorology｜Climate averages・気象警報（気候・警報）", url: "http://www.bom.gov.au/climate/averages/", accessedAt: "2026-07-30" },
    ],
    relatedSlugs: ["area-darwin", "area-overview", "farm-second-visa", "second-visa-guide", "safety-emergency", "housing-guide"],
    updatedAt: "2026-07-30",
    published: true,
  },
];
