import type { Article, ArticleCategory } from "@/types/article";
import type { ForumCategory, ForumComment, ForumPost } from "@/types/forum";
import type { Report } from "@/types/report";
import type { FeedbackRequest } from "@/types/feedback";

export const articleCategories: Array<{ slug: ArticleCategory; name: string }> = [
  { slug: "visa", name: "ビザ" },
  { slug: "preparation", name: "渡航前準備" },
  { slug: "arrival", name: "渡航後" },
  { slug: "tfn", name: "TFN" },
  { slug: "abn", name: "ABN" },
  { slug: "super", name: "Superannuation" },
  { slug: "tax-return", name: "タックスリターン" },
  { slug: "bank", name: "銀行口座" },
  { slug: "sim", name: "SIM" },
  { slug: "housing", name: "家探し" },
  { slug: "jobs", name: "仕事探し" },
  { slug: "farm", name: "ファーム" },
  { slug: "second-visa", name: "セカンドビザ" },
  { slug: "uber-eats", name: "Uber Eats" },
  { slug: "doordash", name: "DoorDash" },
  { slug: "cars", name: "車・交通" },
  { slug: "food", name: "食事" },
  { slug: "clothing", name: "服装" },
];

export const articles: Article[] = [
  {
    id: "a1",
    title: "オーストラリアワーホリ完全ガイド",
    slug: "whv-complete-guide",
    category: "visa",
    description: "ワーホリ準備から現地生活までの全体像をまとめた入門記事です。",
    content: [
      "ワーキングホリデーは準備の順番を押さえることで、失敗リスクを大きく下げられます。",
      "このガイドでは、ビザ申請、渡航前準備、到着後手続き、仕事探しまでを段階的に紹介します。",
    ],
    steps: [
      { title: "ビザ要件を確認", description: "年齢、資金、パスポート有効期限をチェックします。" },
      { title: "渡航計画を作成", description: "都市、予算、仕事方針を先に決めます。" },
      { title: "到着後タスクを把握", description: "TFN、銀行口座、SIMを優先度順に実施します。" },
    ],
    warnings: ["ビザ制度は変更される場合があるため、必ず公式情報を確認してください。"],
    relatedSlugs: ["visa-application", "arrival-checklist"],
    updatedAt: "2026-06-09",
    published: true,
  },
  {
    id: "a2",
    title: "ワーホリビザ申請ステップ",
    slug: "visa-application",
    category: "visa",
    description: "オンライン申請の流れをスクリーン付きで解説します。",
    content: ["ImmiAccount作成後、申請フォーム入力と必要書類提出を行います。"],
    steps: [
      { title: "ImmiAccount作成", description: "公式サイトでアカウント登録します。" },
      { title: "申請フォーム入力", description: "個人情報と滞在計画を入力します。" },
      { title: "申請料支払い", description: "クレジットカードで決済し審査を待ちます。" },
    ],
    relatedSlugs: ["whv-complete-guide"],
    updatedAt: "2026-06-07",
    published: true,
  },
  {
    id: "a3",
    title: "オーストラリア到着後チェックリスト",
    slug: "arrival-checklist",
    category: "arrival",
    description: "到着1週間で必須の手続きを整理しました。",
    content: ["優先順位はTFN申請、銀行口座、SIM契約、住居確保です。"],
    steps: [
      { title: "TFN申請", description: "ATOサイトでオンライン申請します。" },
      { title: "銀行口座開設", description: "必要書類を持って支店で開設します。" },
      { title: "SIM契約", description: "通信キャリアを比較して契約します。" },
    ],
    relatedSlugs: ["tfn-guide", "abn-guide"],
    updatedAt: "2026-06-05",
    published: true,
  },
  {
    id: "a4",
    title: "TFN（タックスファイルナンバー）取得ガイド",
    slug: "tfn-guide",
    category: "tfn",
    description: "給与受け取りに必須のTFNをオンラインで取得する方法。",
    content: ["TFNはATOの公式サイトから無料で申請できます。郵送で約2週間で届きます。"],
    steps: [
      { title: "ATOサイトへアクセス", description: "オンライン申請ページを開きます。" },
      { title: "個人情報を入力", description: "パスポートと滞在先住所を入力します。" },
      { title: "郵送を待つ", description: "TFN通知の到着を待ちます。" },
    ],
    relatedSlugs: ["abn-guide", "tax-return-guide"],
    updatedAt: "2026-06-05",
    published: true,
  },
  {
    id: "a5",
    title: "ABN取得とギグワークの始め方",
    slug: "abn-guide",
    category: "abn",
    description: "Uber EatsなどのギグワークにはABNが必要です。取得手順を解説します。",
    content: ["ABNはABRの公式サイトから無料で申請できます。Sole Traderとして登録します。"],
    steps: [
      { title: "ABRサイトで申請", description: "Sole Traderを選び申請します。" },
      { title: "業種を選択", description: "デリバリー等の業種を選びます。" },
      { title: "ABN発行", description: "即時または数日でABNが発行されます。" },
    ],
    warnings: ["ABNでの収入は確定申告が必要です。記録を必ず残しましょう。"],
    relatedSlugs: ["tax-return-guide", "uber-eats-guide"],
    updatedAt: "2026-06-04",
    published: true,
  },
  {
    id: "a6",
    title: "タックスリターンの基本",
    slug: "tax-return-guide",
    category: "tax-return",
    description: "確定申告（Tax Return）の時期と必要書類を整理します。",
    content: ["会計年度は7月1日〜翌年6月30日です。myGov経由でオンライン申告できます。"],
    steps: [
      { title: "Income Statement確認", description: "雇用主からの収入情報を確認します。" },
      { title: "myGovとATOを連携", description: "オンライン申告の準備をします。" },
      { title: "申告して還付を待つ", description: "源泉徴収の還付を受け取ります。" },
    ],
    relatedSlugs: ["super-guide"],
    updatedAt: "2026-06-03",
    published: true,
  },
  {
    id: "a7",
    title: "Superannuation（退職年金）の引き出し",
    slug: "super-guide",
    category: "super",
    description: "ワーホリ終了後にSuperを請求するDASPの手順。",
    content: ["出国後にDASP（Departing Australia Superannuation Payment）として請求できます。"],
    steps: [
      { title: "Super口座を確認", description: "雇用主が積み立てた口座を確認します。" },
      { title: "ビザ失効後に申請", description: "出国後にオンラインで請求します。" },
      { title: "課税後に受領", description: "源泉課税後の金額を受け取ります。" },
    ],
    relatedSlugs: ["tax-return-guide"],
    updatedAt: "2026-06-02",
    published: true,
  },
  {
    id: "a8",
    title: "Uber Eats配達員の始め方",
    slug: "uber-eats-guide",
    category: "uber-eats",
    description: "ギグワークの代表格Uber Eatsの登録から稼働まで。",
    content: ["ABN、対応バッグ、配達手段の保険を準備してから登録します。"],
    steps: [
      { title: "ABN取得", description: "Sole TraderとしてABNを取得します。" },
      { title: "アプリ登録", description: "本人確認と配達手段を登録します。" },
      { title: "稼働開始", description: "ピークタイムを狙って配達します。" },
    ],
    warnings: ["配達中の事故に備え、保険加入を強く推奨します。"],
    relatedSlugs: ["abn-guide", "doordash-guide"],
    updatedAt: "2026-06-01",
    published: true,
  },
  {
    id: "a9",
    title: "DoorDash配達の基礎",
    slug: "doordash-guide",
    category: "doordash",
    description: "DoorDashの登録と稼働のコツ。",
    content: ["DoorDashもABNが必要です。エリアによって需要が大きく変わります。"],
    steps: [
      { title: "アカウント作成", description: "必要書類とABNを登録します。" },
      { title: "エリア選定", description: "需要の高いエリアで稼働します。" },
      { title: "評価を維持", description: "高評価を保ち配達機会を増やします。" },
    ],
    relatedSlugs: ["uber-eats-guide"],
    updatedAt: "2026-05-30",
    published: true,
  },
  {
    id: "a10",
    title: "ファームジョブの探し方とセカンドビザ",
    slug: "farm-second-visa",
    category: "farm",
    description: "セカンドビザ対象のSpecified Workを探す方法。",
    content: ["88日間の規定労働でセカンドビザ申請資格が得られます。対象地域と職種を確認しましょう。"],
    steps: [
      { title: "対象地域を確認", description: "郵便番号で対象地域を確認します。" },
      { title: "求人に応募", description: "農場やホステル経由で仕事を探します。" },
      { title: "Payslipを保管", description: "申請に必要な証拠を必ず保管します。" },
    ],
    warnings: ["無給労働やノーペイトライアルの誘いには注意してください。"],
    relatedSlugs: ["whv-complete-guide"],
    updatedAt: "2026-05-29",
    published: true,
  },
  {
    id: "a11",
    title: "シェアハウス探しと詐欺対策",
    slug: "housing-guide",
    category: "housing",
    description: "Facebook Marketplaceでの家探しと詐欺回避。",
    content: ["内見前の送金は避け、必ず実際に部屋を確認してから契約しましょう。"],
    steps: [
      { title: "予算とエリア決定", description: "通勤と治安を考慮して決めます。" },
      { title: "内見を予約", description: "複数物件を比較します。" },
      { title: "契約とBond", description: "条件を確認して契約します。" },
    ],
    warnings: ["内見前に送金を求める物件は詐欺の可能性が高いです。"],
    relatedSlugs: ["whv-complete-guide"],
    updatedAt: "2026-05-28",
    published: true,
  },
  {
    id: "a12",
    title: "車の購入とRego・保険",
    slug: "cars-guide",
    category: "cars",
    description: "ワーホリでの車購入、登録、保険の基礎。",
    content: ["州ごとにRego（登録）とRoadworthy Certificateのルールが異なります。"],
    steps: [
      { title: "車を選ぶ", description: "走行距離と整備履歴を確認します。" },
      { title: "Rego名義変更", description: "州の運輸局で名義を変更します。" },
      { title: "保険加入", description: "CTP以外の任意保険も検討します。" },
    ],
    relatedSlugs: ["whv-complete-guide"],
    updatedAt: "2026-05-27",
    published: true,
  },
];

export const forumCategories: ForumCategory[] = [
  { id: "c1", name: "家探し", slug: "housing", description: "シェアハウスや内見情報を共有" },
  { id: "c2", name: "仕事探し", slug: "jobs", description: "求人、面接、履歴書の相談" },
  { id: "c3", name: "ファームジョブ", slug: "farm", description: "地域や時給、体験談" },
  { id: "c4", name: "車・レンタカー", slug: "cars", description: "車購入・売買・トラブル相談" },
  { id: "c5", name: "ビザ", slug: "visa", description: "ビザ申請や条件の質問" },
  { id: "c6", name: "セカンドビザ", slug: "second-visa", description: "Specified Workや申請の情報" },
  { id: "c7", name: "ギグワーク", slug: "gig", description: "Uber Eats・DoorDashの相談" },
  { id: "c8", name: "税金", slug: "tax", description: "TFN・ABN・確定申告の相談" },
  { id: "c9", name: "生活相談", slug: "life", description: "現地生活の困りごと" },
  { id: "c10", name: "売ります・買います", slug: "buy-sell", description: "不用品の売買" },
  { id: "c11", name: "旅行", slug: "travel", description: "国内旅行や観光情報" },
  { id: "c12", name: "雑談", slug: "general", description: "自由な雑談スペース" },
];

export const forumPosts: ForumPost[] = [
  {
    id: "p1",
    categorySlug: "housing",
    userId: "u1",
    authorName: "Mika",
    title: "シドニーで女性向けシェアハウスを探しています",
    body: "City周辺で週350ドル前後の物件情報を探しています。",
    isHidden: false,
    likeCount: 4,
    createdAt: "2026-06-08",
  },
  {
    id: "p2",
    categorySlug: "jobs",
    userId: "u2",
    authorName: "Ken",
    title: "カフェのトライアル面接で準備すべきこと",
    body: "英語自己紹介とトレー持ち運びは事前練習が有効でした。",
    isHidden: false,
    likeCount: 7,
    createdAt: "2026-06-07",
  },
  {
    id: "p3",
    categorySlug: "gig",
    userId: "u3",
    authorName: "Sho",
    title: "Uber Eatsの稼ぎ時を教えてください",
    body: "ブリスベンでの平日と週末の差を知りたいです。",
    isHidden: false,
    likeCount: 2,
    createdAt: "2026-06-06",
  },
];

export const forumComments: ForumComment[] = [
  {
    id: "cm1",
    postId: "p1",
    userId: "u2",
    authorName: "Ken",
    body: "Facebook Marketplaceでも見つかります。内見前に写真確認がおすすめです。",
    isHidden: false,
    createdAt: "2026-06-08",
  },
];

export const reports: Report[] = [
  {
    id: "r1",
    reporterName: "Mika",
    targetType: "post",
    targetId: "p3",
    reason: "スパムの可能性があります。",
    status: "pending",
    createdAt: "2026-06-08",
  },
];

export const feedbackRequests: FeedbackRequest[] = [
  {
    id: "f1",
    userId: "u1",
    authorName: "Mika",
    type: "article_request",
    pageUrl: "/farm",
    title: "ファームの地域別時給情報がほしい",
    body: "地域ごとの時給目安をまとめた記事を希望します。",
    status: "pending",
    createdAt: "2026-06-08",
  },
];
